// Spinner verbs for loading messages
export const SPINNER_VERBS = [
  'Accomplishing',
  'Actioning',
  'Actualizing',
  'Architecting',
  'Baking',
  'Beaming',
  'Brewing',
  'Calculating',
  'Cerebrating',
  'Clauding',
  'Coalescing',
  'Cogitating',
  'Combobulating',
  'Composing',
  'Computing',
  'Concocting',
  'Considering',
  'Contemplating',
  'Cooking',
  'Crafting',
  'Creating',
  'Crunching',
  'Crystallizing',
  'Deciphering',
  'Deliberating',
  'Determining',
  'Doing',
  'Effecting',
  'Elucidating',
  'Envisioning',
  'Fermenting',
  'Flowing',
  'Forging',
  'Forming',
  'Generating',
  'Hashing',
  'Hatching',
  'Ideating',
  'Imagining',
  'Improvising',
  'Incubating',
  'Inferring',
  'Manifesting',
  'Marinating',
  'Mulling',
  'Musing',
  'Orchestrating',
  'Percolating',
  'Perusing',
  'Pondering',
  'Processing',
  'Propagating',
  'Puzzling',
  'Reasoning',
  'Reticulating',
  'Ruminating',
  'Simmering',
  'Sketching',
  'Spinning',
  'Stewing',
  'Synthesizing',
  'Thinking',
  'Tinkering',
  'Unfurling',
  'Working',
  'Wrangling',
]

// Spinner animation frames
export const SPINNER_FRAMES = ['⠋', '⠙', '⠹', '⠸', '⠼', '⠴', '⠦', '⠧', '⠇', '⠏']

// Special symbols
export const TEARDROP_ASTERISK = '✶'

// Time constants for stall detection
export const STALL_THRESHOLD_MS = 3000 // Start showing red after 3s of no activity
export const STALL_FADE_DURATION_MS = 2000 // Fade to red over 2 seconds
